repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: mixed-line-ending
      - id: no-commit-to-branch
        args: ["--branch", "main"]
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.6
    hooks:
      - id: ruff
        name: ruff check
        args: [--fix]
      - id: ruff-format
        name: ruff format
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: npm run prettier:check
        language: node
        pass_filenames: false
      - id: grammar-tests
        name: grammar tests
        entry: npm run grammar:test
        language: node
        pass_filenames: false
      - id: eslint
        name: eslint
        entry: npm run eslint
        language: node
      - id: npm-lockfile-check
        name: npm lockfile check
        entry: npm run check:lockfile
        language: node
        files: package.json
        pass_filenames: false
