repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: mixed-line-ending
      - id: no-commit-to-branch
        args: ["--branch", "main"]
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
  - repo: local
    hooks:
      - id: run-prettier-check
        name: Run prettier check
        entry: npm run check:prettier
        language: node
        pass_filenames: false
      - id: run-grammar-tests
        name: Run grammar tests
        entry: npm run test:grammar
        language: node
        pass_filenames: false
