# This workflow runs the following jobs:
# - ruff
# - prettier-eslint
# - codespell
# - gen-from-dfn
# - check-lockfile
# - grammar-tests
# - vscode-integration-tests

name: CI
permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run ruff linter
        uses: astral-sh/ruff-action@v3
        with:
          args: check --output-format=github
      - name: Run ruff formatter
        uses: astral-sh/ruff-action@v3
        with:
          args: format --diff

  prettier-eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install project dependencies
        run: npm ci
      - name: Run prettier check
        run: npm run prettier:check
      - name: Run eslint
        run: npm run eslint

  codespell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run codespell
        uses: codespell-project/actions-codespell@v2

  gen-from-dfn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download DFN files from MF6 repository
        run: utils/download_dfn.sh
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Regenerate from templates
        run: uv run utils/gen_from_dfn.py
      - name: Check for changes
        run: git diff --exit-code

  check-lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm ci
      - name: Check lockfile
        run: npm run check:lockfile

  grammar-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm ci
      - name: Run grammar tests
        run: npm run grammar:test

  vscode-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm ci
      - name: Run integration tests
        run: xvfb-run -a npm test
