# This workflow runs Ruff, Prettier, Codespell on the repository.

name: Lint-Format

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - develop

jobs:
  ruff-lint-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run ruff linter
        uses: astral-sh/ruff-action@v3
        with:
          args: check --output-format=github
      - name: Run ruff formatter
        uses: astral-sh/ruff-action@v3
        with:
          args: format --diff

  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install project dependencies
        run: npm ci
      - name: Run prettier check
        run: npm run check:prettier

  codespell:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run codespell
        uses: codespell-project/actions-codespell@v2
