# This workflow checks if file generation from templates is correct.

name: Jinja Templates

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  gen_from_templates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Regenerate from templates
        run: uv run utils/generate_from_templates.py

      - name: Check for changes
        run: git diff --exit-code
