# This workflow checks if file generation from templates is correct.

name: Jinja Templates

on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  gen_from_templates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone MODFLOW repository
        uses: actions/checkout@v4
        with:
          repository: "MODFLOW-USGS/modflow6"
          path: "modflow6"
          ref: "6.6.0"
          sparse-checkout: "doc/mf6io/mf6ivar/dfn"

      - name: Copy DFN files
        run: |
          mkdir -p data/dfn
          cp  modflow6/doc/mf6io/mf6ivar/dfn/* data/dfn/

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Regenerate from templates
        run: uv run utils/generate_from_templates.py

      - name: Check for changes
        run: git diff --exit-code
